authorName: default
experimentName: example_sin
maxExecDuration: 5m
maxTrialNum: 100
trialConcurrency: 10
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
    parallel_optimize: True
    constant_liar_type: min
trial:
  command: python3 study.py
  codeDir: .
  gpuNum: 0
